all:
	gcc Xerife.c -o Xerife ../julgar/julgar.c ../cadastro_questao/cad_questao.c ../cadastro/cadastro.c ../login/login.c ../cadastro_questao/control_list.c ../mostrar_lista/mostrar_lista.c ../mostrar_lista/struct_list.c ../login/lista_login.c ../cadastro_lista/cadastro_lista.c `pkg-config --cflags --libs gtk+-3.0`
	
	./Xerife